packages:
  - packages/*
  - docs

ignoredBuiltDependencies:
  - simple-git-hooks

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma
  - unrs-resolver
  - vue-demi
